Feature #18/need more info user
cherrypick-project/back-end pull request #19
Opened 2022-04-20 15:32 UTC by dhdydtn91

추가정보 저장 로직 구현했습니다.
근데 테스트 작성이 조금 까다로워서 UserServiceImplTest쪽은 @SpringBoot로 작성하게 됬네요
단위 테스트로 변경하려면 로직에서 권한 설정하는 부분을 따로 분리하거나 Facade로 이동시켜야 할것같은데 경덕님은 어떻게 생각하시나요?

2022-05-05 01:26 UTC, sinkyoungdeok requested changes
고생하셨습니다~ 
필요없는 공백이 좀 보여서 제거 요청 드립니다

2022-05-05 01:26 UTC, sinkyoungdeok commented on src/main/java/com/cherrypick/backend/presentation/auth/AuthDto.java
> +
여기 공백 제거 부탁드립니다~

2022-05-05 01:26 UTC, sinkyoungdeok commented on src/main/java/com/cherrypick/backend/presentation/auth/AuthDto.java
> +
여기 공백 제거 부탁드립니다~

2022-05-06 14:42 UTC, dhdydtn91 commented on src/main/java/com/cherrypick/backend/presentation/auth/AuthDto.java
> +
[139bb74](https://github.com/cherrypick-project/back-end/pull/19/commits/139bb74eac594b980b93765fa3896c30ce227624) 피드백 반영했습니다!

2022-05-06 14:42 UTC, dhdydtn91 commented on src/main/java/com/cherrypick/backend/infrastructure/user/UserReaderImpl.java
[139bb74](https://github.com/cherrypick-project/back-end/pull/19/commits/139bb74eac594b980b93765fa3896c30ce227624) 피드백 반영했습니다!

2022-05-07 11:10 UTC, sinkyoungdeok approved these changes
고생하셨습니다~

2022-05-07 11:10 UTC, merged